services:
  asyncio-chainable:
    container_name: asyncio-chainable
    image: asyncio-chainable
    build:
      context: .
      args:
        POETRY_INSTALL_ARGS: "--with dev --all-extras"
        GEMFURY_TOKEN: "${GEMFURY_TOKEN}"
        EXTRAS: "[test]"
    entrypoint: ["bash"]
    volumes:
      - .:/asyncio-chainable
